## Numpy

In [8]:
import numpy as np
a = np.array([1, 2, 3])  #creating an array using numpy
print(a)
print(type(a))  #printing data type of a
print(a.ndim)  #printing dimension of the array
print(a.shape)
print(len(a)) #printing length of array
np.arange(15).reshape(3, 5)  #filling a matrix with 1st 15 whole numbers

[1 2 3]
<class 'numpy.ndarray'>
1
(3,)
3


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
import numpy as np
print(np.linspace(1, 8, 4))  #printing numbers in the range spaced equally
print()
print(np.linspace(1, 8, 4, endpoint=False))  #same as abovr except dropping last element
print()
print(np.random.randint(1, 100, 6))  #inserting random numbers in array
print()
print(np.random.randint(1, 100, 6).reshape(3, 2))  #inserting random numbers in a matrix
print()
print(np.random.rand(4))
print()
print(np.eye(5))  #printing identity matrix of 5x5
print()
print(np.zeros)
print()
print(np.random.randn(3, 2))
print()
print(np.empty((3,3)))
print()
print(np.ones((2,3,4), dtype=np.int16))  #printing 2 matrices of 4x3 size with 1's
print()
print(np.array([[1,2],[3,4]],dtype=complex))  #printing complex matrix
print()
print(np.array([(1.5,2,3),(4,5,6)]))

[1.         3.33333333 5.66666667 8.        ]

[1.   2.75 4.5  6.25]

[24 95  6 44 91 16]

[[58 97]
 [93 69]
 [81  1]]

[0.36893509 0.29452551 0.59304117 0.70852499]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

<built-in function zeros>

[[-1.72361578  0.43986629]
 [ 1.34056506  2.46816518]
 [-0.26350995 -0.41998908]]

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.61258574e-321]
 [1.06806669e-306 1.33511969e-306 1.08224926e-312]]

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [43]:
A = np.array([[2, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A+B)  #sum of 2 matrices
print()
print(A*B)  #element-wise multiplication of matrix
print()
print(A@B)  #matrix multiplication
print()
print(A.dot(B)) #dot product of 2 matrices
print()
print(B.T)  #transpose
print()
print(A.flatten())  #printing matrix in a single dimension array
print()
print(B<3)  #checking whether each element of B is < 3 or not
print()
print(A.sum())  #sum of all elements
print()
print(A.sum(axis=0)) #sum of each column
print()
print(A.sum(axis=1)) #sum of each row
print()
print(A.cumsum(axis=1))  #cumulative sum of rows
print()
print(A.max())  #maximum element of A
print()
print(A.min())  #minimum element of A
print()

[[4 1]
 [3 5]]

[[4 0]
 [0 4]]

[[7 4]
 [3 4]]

[[7 4]
 [3 4]]

[[2 3]
 [0 4]]

[2 1 0 1]

[[ True  True]
 [False False]]

4

[2 2]

[3 1]

[[2 3]
 [0 1]]

2

0



In [52]:
a = np.arange(4)**3  #inserting cube of all numbers from 0-3
print(a)
print()
print(a[2])
print()
print(a[::-1])  #reversing the array
print()
print(a[0:4:1])
print()
print(a[1,...])
print()
print(a[a>5])  #printing elements of a > 5
print()
x = a[0:4]
print(x)
print()
x[:] = 99  #replacing all elements of x with 99
print(x)

[ 0  1  8 27]

8

[27  8  1  0]

[ 0  1  8 27]

1

[ 8 27]

[ 0  1  8 27]

[99 99 99 99]


## Pandas

In [54]:
import numpy as np
import pandas as pd
arr = np.array([1, 3, 5, 7, 9])
s2 = pd.Series(arr)  #representing an array as series
print(s2)
print(type(s2))

0    1
1    3
2    5
3    7
4    9
dtype: int32
<class 'pandas.core.series.Series'>


In [56]:
import numpy as np
import pandas as pd
s2 = pd.Series([10, 20, 30])  #array as series
print(s2)
print(type(s2))
#array as dataframe
s3 = pd.DataFrame([[1,2],[3,4]], columns=['A','B'], index=['C','D'])
print(s3)
print(type(s3))

0    10
1    20
2    30
dtype: int64
<class 'pandas.core.series.Series'>
   A  B
C  1  2
D  3  4
<class 'pandas.core.frame.DataFrame'>


In [84]:
s4 = pd.DataFrame(np.random.randn(20,7), columns=['A', 'B', 'C', 'D', 'E', 'F', 'G'])
print(s4)
print()
print(s4[(5<s4.index) & (s4.index <10)])  #s4 with values that satisfy both conditions
print()
print(s4.head())  #first 5 rows of s4
print()
print(s4.tail())  #last 5 rows of s4
print()
s4.describe()  #statistical information of data 
print()
print(s4['B'])  #data of 'B' column
print()
print(s4[['B', 'E']])  #data of 'B and 'E' columns
print()
print(s4[0:3])  #data of 1-3 columns
print()
print(s4.iloc[0:3])  #data of 1-3 columns
print()
print(s4.loc[[2,3], ['A', 'B']])  #value of row 2,3 column 'A', 'B'
print()
print(s4[2<s4])  #s4 with values matching conditions
print()
print(s4.mean())  #means of each column
print()
print(s4.mean(1))  #mean of each row
print()
print(s4.drop(5, axis=0))  #delete row 5
print()
print(s4.drop('D', axis=1))  #delete 'D' column
print()
print(s4.drop('D', axis=1, inplace=True))  #delete 'D' column permanently
print()
s4['H'] = np.random.rand(20, 1)  #add a new column of same length.
print(s4)

           A         B         C         D         E         F         G
0   1.115306 -0.066649 -1.992673 -0.835102  1.075631 -0.397623 -1.262792
1   0.136541 -0.119837  0.401321 -0.618164  0.926294 -1.081542 -0.051349
2  -0.705208  0.754774  1.053043 -0.553946  1.855873 -0.637474  0.483710
3   1.633270  1.453975 -0.601307 -0.530352 -0.018557  2.086982  0.796934
4   0.617132 -0.293587  0.281803 -2.207521  1.737118 -0.870362  0.618354
5  -0.986616 -2.037638  0.377398  1.593169  2.105297 -1.858218 -0.079327
6   0.384735  1.035974  0.448350  0.413172 -0.506702 -0.739219 -1.666765
7  -0.623702  0.915791 -2.579637 -1.003833 -0.870134  0.046289  0.617022
8   0.762036 -1.525645 -1.456908  0.527591 -1.268786  0.264577  1.797605
9   0.097387 -0.968237  0.236689 -1.682411  0.854894  0.456322 -0.020977
10 -0.400953 -0.389121  0.136594 -0.748827 -1.482246  1.523900  0.239273
11 -0.727293 -1.141788  0.325495 -0.772224 -0.971574 -1.379798 -0.629739
12 -0.616461  0.425890 -0.229244 -0.151725  0.35915